import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from 'react-hot-toast'
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import CartContextProvider from "./_Component/Context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MySessionProvider>
          <CartContextProvider>
            <Toaster/>
            <Navbar/>
            <main className="container mx-auto min-h-screen">
              {children}
            </main>
            <Footer/>
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );

}
